site_name: FOOSIEngine Docs
site_url: https://realblobii.github.io/FOOSIEngine
theme:
  name: material
nav:
  - Home: index.md
  - Engine: engine.md
  - Objects: objects.md
  - Input: input.md
  - Render: render.md
  - API: api.md
  - Build: build.md
  - Conventions: conventions.md
